<?php

#function for admin munu
 function contactform_perm() {
 return array('administer menu');
}

# create the admin menu link ad call back
function contactform_menu() {
  $items['admin/contactform'] = array(
    'title' => 'Contact Form',
    'description' => "Test module.",
    'page callback' => 'contact_list',
    'access callback' => 'user_access',
    'access arguments' => array('administer menu'),
  );
$items['admin/contactform/list'] = array(
    'title' => 'List',    
    'type' => MENU_DEFAULT_LOCAL_TASK,
);
$items['admin/contactform/add'] = array(
    'title' => 'Add',
    'description' => "Test module.",
    'page callback' => 'my_function',
    'access arguments' => array('access staff content'),
    'type' => MENU_LOCAL_TASK,
);
$items['admin/contactform/delete/%'] = array(
    'title' => 'Delete Contact',
    'page callback' => 'delete_contact',
    //'page arguments' => array(3),
    'access callback' => 'user_access',
    //'access arguments' => array('access staff content'),
    'description' => 'Delete Contact',
    'type' => MENU_CALLBACK,
);


return $items;
}
# call

function my_function(){
return drupal_get_form('add_contact_form');
}

# form field
function add_contact_form(){
$form['#redirect'] = 'admin/contactform/list';
$form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Your Name '),
    '#required' => TRUE,
    '#maxlength' => 20,
  );
$form['dob'] = array(
    '#type' => 'date',
    '#title' => t('Enter Your Data Of Birth  '),
    '#required' => TRUE,
  );
$form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Your E-Mail  '),
    '#required' => TRUE,
    '#maxlength' => 25,
  );
$form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter Your phone  '),
    '#required' => TRUE,
    '#maxlength' => 10,
   
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

#inset the submited values to the databases

function add_contact_form_submit($form_id, $form_values){
$name = $form_values['values']['name'];
$email = $form_values['values']['email'];
$phone = $form_values['values']['phone'];
$date = $form_values['values']['dob'];
$dob=$date['year'].'-'.$date['month'].'-'.$date['day'];

//$result=db_query="INSERT INTO contactform_test {name,dob,email,phone} values(".$name,$dob,$email,$phone.")";
//$result=db_query($insert_query,$name,$dob,$email,$phone);
//$result=db_query("INSERT INTO {contactform_test} (name,dob,email,phone) VALUES ('%s', '%s', '%s', %d)", $form->name,$dob,$email,$phone) or die("unable to insert");
$insert_query = "INSERT INTO {contactform_test} SET name = '%s', dob = '%s', email = '%s', phone = %d";
    $result = db_query($insert_query, $name, $dob, $email, $phone)or die("unable to insert");
if($result){
echo $name.$dob.$email.$phone;
drupal_set_message('one row successfully inserted in to databases!');
}
}


function contact_list(){

  $header = array('Name', 'D.O.B', 'E-Mail', 'Phone');
  $row = array();
  $destination = drupal_get_destination();
  $tablesort = tablesort_sql($header);
  $query = "SELECT * FROM {contactform_test} ORDER BY cfid DESC";
  $result=pager_query($query . $tablesort);
  while ($item = db_fetch_object($result,null)) {
    $row[]=array($item->name,$item->dob,$item->email,$item->phone,l("Edit",'admin/contactform/edit/'. $item->cfid),l("Delete", 'admin/contactform/delete/'. $item->cfid, array(/*"query" => $destination,*/ "attributes" => array("onClick" => "return confirm('Are you sure you want to delete this student record?');"))));
   }
      
   
  $output = theme('table',$header,$row);
  if (count($row) == 0) {
    $output .= '<div style="color:red;text-align:center;">No Contact List Available.</div>';
  }
  $output .= theme('pager');
  return $output;


drupal_set_message('contact has been activated successfully!');
}

# Form Field validate
function add_contact_form_validate($form, $form_values){
$name = $form_values['values']['name'];
$email = $form_values['values']['email'];
$phone = $form_values['values']['phone'];
$dob = $form_values['values']['dob'];

#validate name
if (preg_match("/[^a-zA-Z]/",$name)){
   form_set_error('name', t('Enter the Valied name'.$dob['year'].$dob['month'].$dob['day']));
}

#validate the Email
if (!preg_match("/([\w\-]+\@[\w\-]+\.[\w\-]+)/",$email)){                    
   form_set_error('email', t('Enter the Valied E-mail Address'));
}

#validate phone number
if (preg_match("/\D/",$phone)){
    form_set_error('phone', t('Enter the Valied phone Number'));
}

}

function delete_contact(){
echo "i am in delete function";

}

#set what will done while click the submit button

/*
function my_form_submit($form, $form_values) {
  $sub1 = $form_values['values']['sub1'];
  $sub2 = $form_values['values']['sub2'];
  $message = 'Your session has been saved'.'Subject1 values='.$sub1.'   Subject2 values='.$sub2;
  drupal_set_message(t($message.$output));
}

#validate a form
function my_form_validate($form, $form_values){
$sub1 = $form_values['values']['sub1'];
$sub2 = $form_values['values']['sub2'];
if (is_numeric($sub1)){
   form_set_error('sub', t('is numaric'));
}
else{
form_set_error('sub', t('enter numarick values'));
}

}
*/


#validate url
/*  
$url = htmlspecialchars($_POST['website']);
if (!preg_match("/^(https?:\/\/+[\w\-]+\.[\w\-]+)/i",$url))
{
    die("URL address not valid");
}*/
  ?>
